export const TEXT_TYPE = {
  HEADER_1: 'HEADER_1',
  HEADER_2: 'HEADER_2',
  HEADER_3: 'HEADER_3',
  HEADER_4: 'HEADER_4',
  HEADER_5: 'HEADER_5',
  HEADER_6: 'HEADER_6',
  CONTENT_HEADER: 'CONTENT_HEADER',
  BODY_1: 'BODY_1',
  BODY_2: 'BODY_2',
  CONTENT: 'CONTENT',
  NOTE: 'NOTE',
  BOLD: 'BOLD',
};
